### ISSUE TITLE
Installation docs don't work on Laravel 6 and up

### ISSUE THREAD

**Issue by yoeriboven** [vanilophp/docs#11]
Laravel 6 has the `php artisan make:auth` command removed.

Instead the following commands have to be run:

```bash
composer require laravel/ui --dev
php artisan ui vue --auth
```

Not running these commands means Vue and Popper.js don't get installed while `vendor/konekt/appshell/src/resources/assets/js/appshell.standalone.js` needs those.

Reason I didn't create a PR is because there is a more elegant way to fix this problem. 

Vanilo only works with certain `npm/yarn` packages installed. A command like Laravel does with `php artisan ui vue --auth` adds the required packages to the `packages.json`. This way it doesn't matter if the packages are already installed or not since the command will add the packages to `packages.json`.

If the maintainers of Vanilo want the command; I'll write it. Just let me know which packages are essential for installation.

## Steps to reproduce:

Follow the installation docs (create a new project from scratch).

**Comment by yoeriboven** [comment]
It looks like these issues come from [`artkonekt/appshell`](https://github.com/artkonekt/appshell/blob/master/src/resources/assets/js/appshell.standalone.js). Looking at the files it doesn't seem like they actually use Vue or Popper.js. Someone with more knowledge of that project should reduce these files to their bare necessities as a first step.

Probably only jQuery will remain so for jQuery you'd still need to write a command/preset.

**Comment by fulopattila122** [comment]
Yes it comes from AppShell. Both vue and popper js are required. Vue is being used for example in Customer edit page and popper in product page's property editor.

Recently I've bootstrapped a Vanilo project on Laravel 6.8 and it worked without using laravel/ui.

I'll update the documentation accordingly, but also accept a PR that does that.

**Comment by yoeriboven** [comment]
Okay, I see. 

Surprised you got it working without requiring laravel/ui though since where is Vue declared as a package in that instance?

**Comment by pixelpeter** [comment]
Just installed `vanilo/framework 1.1.1` with `laravel/framework v6.12.0`.

I can confirm it does NOT work without installing `laravel/ui`

Maybe the documentation just needs an update

**Comment by pedro-ssantos** [comment]
Same here, have to install laravel/ui on laravel 7.
