### ISSUE TITLE
Can not create a super user account

### ISSUE THREAD

**Issue by ghost** [vanilophp/docs#13]
Hi. Whenever I want to run this command it gives me an error and exits.

`php artisan appshell:super`

It does not let me to enter user info. It just says aborted and quits to the command prompt.

**Comment by fulopattila122** [comment]
What is the error message you get? Perhaps a screenshot?

**Comment by fulopattila122** [comment]
What PHP and Laravel version do you use?
Are you on Vanilo 1.2 version?

**Comment by fulopattila122** [comment]
Duplicate of vanilophp/framework#78. Fixing it there.

**Comment by fulopattila122** [comment]
I cross-post the solution here as well, but all the details are in vanilophp/framework#78.

This issue affects PHP 7.4.0 on Windows. Upgrading PHP to 7.4.1 or higher should solve the problem.

> https://bugs.php.net/bug.php?id=78883
